package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccessItems generated by hbm2java
 */
@Entity
@Table(name = "access_items", catalog = "SKILL_MNG")
public class AccessItems implements java.io.Serializable {

	private Integer id;
	private Integer controllerId;
	private Integer parentId;
	private String alias;
	private String displayName;
	private String subFunction;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public AccessItems() {
	}

	public AccessItems(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public AccessItems(Integer controllerId, Integer parentId, String alias, String displayName, String subFunction,
			Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.controllerId = controllerId;
		this.parentId = parentId;
		this.alias = alias;
		this.displayName = displayName;
		this.subFunction = subFunction;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CONTROLLER_ID")
	public Integer getControllerId() {
		return this.controllerId;
	}

	public void setControllerId(Integer controllerId) {
		this.controllerId = controllerId;
	}

	@Column(name = "PARENT_ID")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "ALIAS", length = 50)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "DISPLAY_NAME")
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "SUB_FUNCTION")
	public String getSubFunction() {
		return this.subFunction;
	}

	public void setSubFunction(String subFunction) {
		this.subFunction = subFunction;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
