package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeExperienceDetail generated by hbm2java
 */
@Entity
@Table(name = "employee_experience_detail", catalog = "SKILL_MNG")
public class EmployeeExperienceDetail implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private int experienceDetailId;
	private Integer projectId;
	private Boolean status;
	private Boolean type;
	private String description;
	private String unit;
	private Integer lastModifier;
	private Date lastModifiedTime;
	private Date lastAcceptedTime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public EmployeeExperienceDetail() {
	}

	public EmployeeExperienceDetail(int employeeId, int experienceDetailId, Date insertDatetime) {
		this.employeeId = employeeId;
		this.experienceDetailId = experienceDetailId;
		this.insertDatetime = insertDatetime;
	}

	public EmployeeExperienceDetail(int employeeId, int experienceDetailId, Integer projectId, Boolean status,
			Boolean type, String description, String unit, Integer lastModifier, Date lastModifiedTime,
			Date lastAcceptedTime, Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.employeeId = employeeId;
		this.experienceDetailId = experienceDetailId;
		this.projectId = projectId;
		this.status = status;
		this.type = type;
		this.description = description;
		this.unit = unit;
		this.lastModifier = lastModifier;
		this.lastModifiedTime = lastModifiedTime;
		this.lastAcceptedTime = lastAcceptedTime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EMPLOYEE_ID", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "EXPERIENCE_DETAIL_ID", nullable = false)
	public int getExperienceDetailId() {
		return this.experienceDetailId;
	}

	public void setExperienceDetailId(int experienceDetailId) {
		this.experienceDetailId = experienceDetailId;
	}

	@Column(name = "PROJECT_ID")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "TYPE", precision = 1, scale = 0)
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "LAST_MODIFIER")
	public Integer getLastModifier() {
		return this.lastModifier;
	}

	public void setLastModifier(Integer lastModifier) {
		this.lastModifier = lastModifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_TIME", length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_ACCEPTED_TIME", length = 19)
	public Date getLastAcceptedTime() {
		return this.lastAcceptedTime;
	}

	public void setLastAcceptedTime(Date lastAcceptedTime) {
		this.lastAcceptedTime = lastAcceptedTime;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
