package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MailHistory generated by hbm2java
 */
@Entity
@Table(name = "mail_history", catalog = "SKILL_MNG")
public class MailHistory implements java.io.Serializable {

	private Integer id;
	private String mailCode;
	private String mailFrom;
	private String mailTo;
	private String mailCc;
	private String mailBcc;
	private String mailTitle;
	private String mailContent;
	private Date sentDatetime;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public MailHistory() {
	}

	public MailHistory(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public MailHistory(String mailCode, String mailFrom, String mailTo, String mailCc, String mailBcc, String mailTitle,
			String mailContent, Date sentDatetime, Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.mailCode = mailCode;
		this.mailFrom = mailFrom;
		this.mailTo = mailTo;
		this.mailCc = mailCc;
		this.mailBcc = mailBcc;
		this.mailTitle = mailTitle;
		this.mailContent = mailContent;
		this.sentDatetime = sentDatetime;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "MAIL_CODE", length = 100)
	public String getMailCode() {
		return this.mailCode;
	}

	public void setMailCode(String mailCode) {
		this.mailCode = mailCode;
	}

	@Column(name = "MAIL_FROM", length = 40)
	public String getMailFrom() {
		return this.mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	@Column(name = "MAIL_TO", length = 40)
	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	@Column(name = "MAIL_CC", length = 1000)
	public String getMailCc() {
		return this.mailCc;
	}

	public void setMailCc(String mailCc) {
		this.mailCc = mailCc;
	}

	@Column(name = "MAIL_BCC", length = 1000)
	public String getMailBcc() {
		return this.mailBcc;
	}

	public void setMailBcc(String mailBcc) {
		this.mailBcc = mailBcc;
	}

	@Column(name = "MAIL_TITLE", length = 50)
	public String getMailTitle() {
		return this.mailTitle;
	}

	public void setMailTitle(String mailTitle) {
		this.mailTitle = mailTitle;
	}

	@Column(name = "MAIL_CONTENT", length = 1000)
	public String getMailContent() {
		return this.mailContent;
	}

	public void setMailContent(String mailContent) {
		this.mailContent = mailContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENT_DATETIME", length = 19)
	public Date getSentDatetime() {
		return this.sentDatetime;
	}

	public void setSentDatetime(Date sentDatetime) {
		this.sentDatetime = sentDatetime;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
