package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillLevel generated by hbm2java
 */
@Entity
@Table(name = "skill_level", catalog = "SKILL_MNG")
public class SkillLevel implements java.io.Serializable {

	private Integer id;
	private String groupName;
	private Integer levelGroup;
	private String levelName;
	private String levelValue;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillLevel() {
	}

	public SkillLevel(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public SkillLevel(String groupName, Integer levelGroup, String levelName, String levelValue, Boolean activeFlg,
			Date insertDatetime, Date updateDatetime) {
		this.groupName = groupName;
		this.levelGroup = levelGroup;
		this.levelName = levelName;
		this.levelValue = levelValue;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "GROUP_NAME", length = 10)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "LEVEL_GROUP")
	public Integer getLevelGroup() {
		return this.levelGroup;
	}

	public void setLevelGroup(Integer levelGroup) {
		this.levelGroup = levelGroup;
	}

	@Column(name = "LEVEL_NAME", length = 50)
	public String getLevelName() {
		return this.levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	@Column(name = "LEVEL_VALUE", length = 10)
	public String getLevelValue() {
		return this.levelValue;
	}

	public void setLevelValue(String levelValue) {
		this.levelValue = levelValue;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
