package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillUnit generated by hbm2java
 */
@Entity
@Table(name = "skill_unit", catalog = "SKILL_MNG")
public class SkillUnit implements java.io.Serializable {

	private Integer id;
	private String prefixUnit;
	private String suffixUnit;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillUnit() {
	}

	public SkillUnit(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	public SkillUnit(String prefixUnit, String suffixUnit, Boolean activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.prefixUnit = prefixUnit;
		this.suffixUnit = suffixUnit;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PREFIX_UNIT")
	public String getPrefixUnit() {
		return this.prefixUnit;
	}

	public void setPrefixUnit(String prefixUnit) {
		this.prefixUnit = prefixUnit;
	}

	@Column(name = "SUFFIX_UNIT")
	public String getSuffixUnit() {
		return this.suffixUnit;
	}

	public void setSuffixUnit(String suffixUnit) {
		this.suffixUnit = suffixUnit;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
