package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillGroup generated by hbm2java
 */
@Entity
@Table(name = "skill_group", catalog = "SKILL_MNG")
public class SkillGroup implements java.io.Serializable {

	private Integer id;
	private int fieldId;
	private String skillGroupName;
	private Short displayOrder;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillGroup() {
	}

	public SkillGroup(int fieldId, Date insertDatetime) {
		this.fieldId = fieldId;
		this.insertDatetime = insertDatetime;
	}

	public SkillGroup(int fieldId, String skillGroupName, Short displayOrder, Boolean activeFlg, Date insertDatetime,
			Date updateDatetime) {
		this.fieldId = fieldId;
		this.skillGroupName = skillGroupName;
		this.displayOrder = displayOrder;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "FIELD_ID", nullable = false)
	public int getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(int fieldId) {
		this.fieldId = fieldId;
	}

	@Column(name = "SKILL_GROUP_NAME", length = 50)
	public String getSkillGroupName() {
		return this.skillGroupName;
	}

	public void setSkillGroupName(String skillGroupName) {
		this.skillGroupName = skillGroupName;
	}

	@Column(name = "DISPLAY_ORDER")
	public Short getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Short displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
