package yav.offshore.skillsheet.orm.po;
// Generated Apr 16, 2018 11:28:39 AM by Hibernate Tools 5.1.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillDetail generated by hbm2java
 */
@Entity
@Table(name = "skill_detail", catalog = "SKILL_MNG")
public class SkillDetail implements java.io.Serializable {

	private Integer id;
	private int skillGroupId;
	private String skillName;
	private Integer parentId;
	private Boolean type;
	private Long evaluationType;
	private Long unitId;
	private Integer skillLevel;
	private Integer rootSkill;
	private Integer lft;
	private Integer rgt;
	private Short displayOrder;
	private Boolean activeFlg;
	private Date insertDatetime;
	private Date updateDatetime;

	public SkillDetail() {
	}

	public SkillDetail(int skillGroupId, Date insertDatetime) {
		this.skillGroupId = skillGroupId;
		this.insertDatetime = insertDatetime;
	}

	public SkillDetail(int skillGroupId, String skillName, Integer parentId, Boolean type, Long evaluationType,
			Long unitId, Integer skillLevel, Integer rootSkill, Integer lft, Integer rgt, Short displayOrder,
			Boolean activeFlg, Date insertDatetime, Date updateDatetime) {
		this.skillGroupId = skillGroupId;
		this.skillName = skillName;
		this.parentId = parentId;
		this.type = type;
		this.evaluationType = evaluationType;
		this.unitId = unitId;
		this.skillLevel = skillLevel;
		this.rootSkill = rootSkill;
		this.lft = lft;
		this.rgt = rgt;
		this.displayOrder = displayOrder;
		this.activeFlg = activeFlg;
		this.insertDatetime = insertDatetime;
		this.updateDatetime = updateDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SKILL_GROUP_ID", nullable = false, length = 10)
	public int getSkillGroupId() {
		return this.skillGroupId;
	}

	public void setSkillGroupId(int skillGroupId) {
		this.skillGroupId = skillGroupId;
	}

	@Column(name = "SKILL_NAME")
	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	@Column(name = "PARENT_ID")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "TYPE", precision = 1, scale = 0)
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "EVALUATION_TYPE", precision = 10, scale = 0)
	public Long getEvaluationType() {
		return this.evaluationType;
	}

	public void setEvaluationType(Long evaluationType) {
		this.evaluationType = evaluationType;
	}

	@Column(name = "UNIT_ID", precision = 10, scale = 0)
	public Long getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Long unitId) {
		this.unitId = unitId;
	}

	@Column(name = "SKILL_LEVEL")
	public Integer getSkillLevel() {
		return this.skillLevel;
	}

	public void setSkillLevel(Integer skillLevel) {
		this.skillLevel = skillLevel;
	}

	@Column(name = "ROOT_SKILL")
	public Integer getRootSkill() {
		return this.rootSkill;
	}

	public void setRootSkill(Integer rootSkill) {
		this.rootSkill = rootSkill;
	}

	@Column(name = "LFT")
	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}

	@Column(name = "RGT")
	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	@Column(name = "DISPLAY_ORDER")
	public Short getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Short displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "ACTIVE_FLG", precision = 1, scale = 0)
	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATETIME", nullable = false, length = 19)
	public Date getInsertDatetime() {
		return this.insertDatetime;
	}

	public void setInsertDatetime(Date insertDatetime) {
		this.insertDatetime = insertDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATETIME", length = 19)
	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
